# Generated by Django 6.1.1 on 2026-10-01 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=160)),
                ('mobile', models.CharField(max_length=16, unique=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('META', 'Meta'), ('GOOGLE', 'Google'), ('CORPORATE', 'Corporate'), ('CAMP', 'Camp'), ('OFFLINE', 'Offline'), ('REFERRAL', 'Referral'), ('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Other')], max_length=20)),
                ('campaign', models.CharField(blank=True, max_length=160)),
                ('care_type', models.CharField(blank=True, choices=[('AT_HOME', 'At Home Screening / Visit'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('HOSPITAL_REFERRED', 'Hospital Referred'), ('SURGERY', 'Surgery'), ('MULTIPLE', 'Multiple')], max_length=24)),
                ('eye_health_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requirement', models.CharField(blank=True, max_length=160)),
                ('requirement_notes', models.TextField(blank=True)),
                ('temperature', models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('FUTURE', 'Future')], default='WARM', max_length=8)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('FOLLOW_UP', 'Follow-up'), ('NOT_PICKED_UP', 'Not picked up'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('WASTE', 'Waste')], default='NEW', max_length=16)),
                ('outcome_reason', models.CharField(blank=True, choices=[('NOT_PICKED_UP', 'Not picked up'), ('BUSY', 'Busy'), ('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('CALLBACK', 'Callback requested'), ('CONVERTED', 'Converted / booked'), ('REJECTED', 'Rejected / not interested'), ('WRONG_NUMBER', 'Wrong number'), ('PRICING_ISSUE', 'Pricing issue'), ('NOT_INTERESTED', 'Not interested'), ('OTHER', 'Other')], max_length=24)),
                ('conversation_happened', models.BooleanField(default=False)),
                ('amount_pitched', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_executed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_executed', models.DateField(blank=True, null=True)),
                ('brochure_sent', models.BooleanField(default=False)),
                ('np_attempt', models.PositiveSmallIntegerField(default=0)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('latest_remark', models.TextField(blank=True)),
                ('priority', models.BooleanField(default=False)),
                ('priority_reason', models.CharField(blank=True, max_length=240)),
                ('created_from', models.CharField(default='Manual', max_length=40)),
                ('external_source_id', models.CharField(blank=True, max_length=200)),
                ('conversion_reason', models.CharField(blank=True, max_length=240)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority', '-created_at'),
                'indexes': [models.Index(fields=['status', 'next_follow_up'], name='lead_lead_status_877298_idx'), models.Index(fields=['temperature', 'status'], name='lead_lead_tempera_2d37fd_idx'), models.Index(fields=['source', 'campaign'], name='lead_lead_source_180e05_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('CALL', 'Call'), ('CALLBACK', 'Callback'), ('BOOKING', 'Booking'), ('OTHER', 'Other')], default='CALL', max_length=12)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='lead.lead')),
            ],
            options={
                'ordering': ('due_at',),
            },
        ),
        migrations.CreateModel(
            name='CallActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('called_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('NOT_PICKED_UP', 'Not picked up'), ('BUSY', 'Busy'), ('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('CALLBACK', 'Callback requested'), ('CONVERTED', 'Converted / booked'), ('REJECTED', 'Rejected / not interested'), ('WRONG_NUMBER', 'Wrong number'), ('PRICING_ISSUE', 'Pricing issue'), ('NOT_INTERESTED', 'Not interested'), ('OTHER', 'Other')], max_length=24)),
                ('remark', models.TextField(blank=True)),
                ('next_action', models.DateTimeField(blank=True, null=True)),
                ('conversation_happened', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='lead.lead')),
            ],
            options={
                'ordering': ('-called_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('AT_HOME', 'At Home Screening / Visit'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('HOSPITAL_REFERRED', 'Hospital Referred'), ('SURGERY', 'Surgery'), ('MULTIPLE', 'Multiple')], max_length=24)),
                ('hospital', models.CharField(blank=True, max_length=160)),
                ('doctor', models.CharField(blank=True, max_length=160)),
                ('amount_pitched', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_booked', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_executed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.BooleanField(default=False)),
                ('insurance_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], default='NOT_APPLICABLE', max_length=16)),
                ('patient_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('NO_SHOW', 'No show')], default='BOOKED', max_length=16)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lead.lead')),
            ],
            options={
                'ordering': ('appointment_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='lead.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
